ITEM = '[data-marker="item"]'
TITLE = '[data-marker="item-title"]'
PRICE = '[data-marker="item-price"]'
PRICE_META = PRICE + ' meta[itemprop="price"]'
ADDRESS = '[data-marker="item-address"]'
DATE = '[data-marker="item-date"]'
IMAGE = '[itemprop="image"]'
DESCRIPTION = '[data-marker="item-description"]'
DISTRICT = '[data-marker="item-address/district"]'
EMPTY = '[data-marker="search-results/empty"]'
