# Generated by Django 5.2.17 on 2026-09-06 09:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('avito', 'Avito'), ('cian', 'CIAN')], max_length=20)),
                ('external_id', models.CharField(max_length=100)),
                ('url', models.TextField()),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('price_per_sqm', models.BigIntegerField(blank=True, null=True)),
                ('rooms', models.IntegerField(blank=True, db_index=True, null=True)),
                ('area', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('floors_total', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('published_text', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('avito', 'Avito'), ('cian', 'CIAN')], max_length=20)),
                ('url', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='listings.listing')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('avito', 'Avito'), ('cian', 'CIAN')], max_length=20)),
                ('mode', models.CharField(choices=[('fast', 'Fast'), ('full', 'Full')], max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('pages_scanned', models.PositiveIntegerField(default=0)),
                ('items_seen', models.PositiveIntegerField(default=0)),
                ('unique_items_seen', models.PositiveIntegerField(default=0)),
                ('new_items', models.PositiveIntegerField(default=0)),
                ('updated_items', models.PositiveIntegerField(default=0)),
                ('price_changes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='listings.searchquery')),
            ],
        ),
        migrations.CreateModel(
            name='ListingSearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_relations', to='listings.listing')),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_relations', to='listings.searchquery')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='search_queries',
            field=models.ManyToManyField(through='listings.ListingSearchQuery', to='listings.searchquery'),
        ),
        migrations.AddConstraint(
            model_name='listingsearchquery',
            constraint=models.UniqueConstraint(fields=('listing', 'search_query'), name='unique_listing_search'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_source_listing'),
        ),
    ]
