# Generated by Django 5.2.17 on 2026-09-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("listings", "0002_backfill_listing_enrichment")]

    operations = [
        migrations.CreateModel(
            name="CianFullScanCheckpoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("search_url", models.TextField()),
                ("next_page", models.PositiveIntegerField(default=1)),
                ("expected_total", models.PositiveIntegerField(blank=True, null=True)),
                ("external_ids", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("search_query", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="cian_full_checkpoint", to="listings.searchquery")),
            ],
        ),
    ]
