# Generated by Django 5.2 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("listings", "0009_source_health_alert")]

    operations = [
        migrations.CreateModel(
            name="SourcePollingControl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(choices=[("avito", "Avito"), ("cian", "CIAN"), ("domclick", "Домклик")], max_length=20, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
