# Generated by Django 5.1.15 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("listings", "0015_manual_domclick_job")]

    operations = [
        migrations.AddField(
            model_name="listing", name="address_override",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing", name="district_override",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="listing", name="microdistrict_override",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
