# Generated by Django 5.1.15 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("listings", "0017_location_directory")]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="location_source",
            field=models.CharField(db_default="parser", default="parser", max_length=20),
        ),
    ]
