# Generated by Django 5.1.15 on 2026-09-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("listings", "0018_location_source_db_default"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="ScoringPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("min_area", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ("floor_min", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("floor_max", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("preferred_districts", models.JSONField(blank=True, default=list)),
                ("prefer_photo", models.BooleanField(default=False)),
                ("market_weight", models.PositiveSmallIntegerField(default=45)),
                ("freshness_weight", models.PositiveSmallIntegerField(default=20)),
                ("data_weight", models.PositiveSmallIntegerField(default=15)),
                ("floor_weight", models.PositiveSmallIntegerField(default=10)),
                ("price_history_weight", models.PositiveSmallIntegerField(default=10)),
                ("preference_weight", models.PositiveSmallIntegerField(default=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="scoring_preference", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
