# Generated by Django 5.2.17 on 2026-09-12 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


TAGS = [
    ("condition", "poor-repair", "Плохой ремонт"), ("condition", "cosmetic-repair", "Нужен косметический ремонт"),
    ("condition", "major-repair", "Нужен капитальный ремонт"), ("condition", "rough-finish", "Черновая отделка"),
    ("condition", "no-finish", "Без отделки"), ("condition", "good-repair", "Хороший ремонт"), ("condition", "move-in-ready", "Можно заехать"),
    ("layout", "bad-layout", "Неудачная планировка"), ("layout", "walk-through-rooms", "Проходные комнаты"),
    ("layout", "small-kitchen", "Маленькая кухня"), ("layout", "little-storage", "Мало мест хранения"), ("layout", "low-ceilings", "Низкие потолки"),
    ("building", "old-building", "Старый дом"), ("building", "poor-entrance", "Плохой подъезд"), ("building", "noisy", "Шумно"),
    ("building", "bad-area", "Плохой район"), ("building", "questionable-location", "Сомнительная локация"), ("building", "far-transport", "Далеко от транспорта"),
    ("building", "good-infrastructure", "Хорошая инфраструктура"), ("building", "good-location", "Удачная локация"),
    ("money", "expensive", "Дорого"), ("money", "negotiation-potential", "Есть потенциал торга"), ("money", "good-price", "Выгодная цена"), ("money", "repair-wont-pay", "Дорогой ремонт не окупится"),
    ("risk", "check-documents", "Требует проверки документов"), ("risk", "questionable-listing", "Сомнительное объявление"), ("risk", "unhelpful-photos", "Фото неинформативны"), ("risk", "needs-viewing", "Нужен просмотр"),
    ("plus", "good-view", "Хороший вид"), ("plus", "bright", "Светлая"), ("plus", "spacious", "Просторная"), ("plus", "good-layout", "Удачная планировка"), ("plus", "matches-criteria", "Подходит под наши критерии"),
]


def create_tags(apps, schema_editor):
    ReviewTag = apps.get_model("listings", "ReviewTag")
    for index, (category, code, name) in enumerate(TAGS):
        ReviewTag.objects.get_or_create(code=code, defaults={"category": category, "name": name, "sort_order": index})


def remove_tags(apps, schema_editor):
    apps.get_model("listings", "ReviewTag").objects.filter(code__in=[row[1] for row in TAGS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_scoringpreference_detail_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('condition', 'Состояние'), ('layout', 'Планировка'), ('building', 'Дом и окружение'), ('money', 'Деньги'), ('risk', 'Риски'), ('plus', 'Плюсы')], max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('category', 'sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ListingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('decision', models.CharField(choices=[('reject', 'Не рассматривать'), ('consider', 'Готов рассмотреть')], max_length=12)),
                ('comment', models.TextField(blank=True)),
                ('interest_reason', models.TextField(blank=True)),
                ('deal_breaker', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_reviews', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.listing')),
                ('tags', models.ManyToManyField(blank=True, related_name='reviews', to='listings.reviewtag')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Consideration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('new', 'Новое'), ('planned', 'Просмотр запланирован'), ('viewed', 'Просмотрено'), ('archived', 'Архив')], default='new', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consideration', to='listings.listingreview')),
            ],
        ),
        migrations.CreateModel(
            name='ListingReviewRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('decision', models.CharField(choices=[('reject', 'Не рассматривать'), ('consider', 'Готов рассмотреть')], max_length=12)),
                ('comment', models.TextField(blank=True)),
                ('interest_reason', models.TextField(blank=True)),
                ('deal_breaker', models.TextField(blank=True)),
                ('tag_codes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='listings.listingreview')),
            ],
        ),
        migrations.CreateModel(
            name='UserListingHide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hides', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_hides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalListingHide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='global_listing_hides', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_hides', to='listings.listing')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('listing',), name='unique_active_global_listing_hide')],
            },
        ),
        migrations.AddConstraint(
            model_name='listingreview',
            constraint=models.UniqueConstraint(fields=('listing', 'author'), name='unique_listing_review_author'),
        ),
        migrations.AddConstraint(
            model_name='listingreview',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 10)), name='review_rating_1_to_10'),
        ),
        migrations.AddConstraint(
            model_name='userlistinghide',
            constraint=models.UniqueConstraint(fields=('listing', 'user'), name='unique_user_listing_hide'),
        ),
        migrations.RunPython(create_tags, remove_tags),
    ]
