# Generated by Django 5.2.17 on 2026-10-07 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0047_telegram_price_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramReviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.CharField(max_length=64)),
                ('telegram_chat_id', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('rating', 'Оценка'), ('tags', 'Теги'), ('interest', 'Причина интереса'), ('deal_breaker', 'Стоп-фактор'), ('comment', 'Комментарий'), ('decision', 'Решение')], default='rating', max_length=20)),
                ('category_index', models.PositiveSmallIntegerField(default=0)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, max_length=12)),
                ('tag_codes', models.JSONField(blank=True, default=list)),
                ('interest_reason', models.TextField(blank=True)),
                ('deal_breaker', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('channel_message_id', models.BigIntegerField(blank=True, null=True)),
                ('channel_chat_id', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_review_sessions', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_review_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('telegram_user_id', 'listing'), name='unique_telegram_review_session')],
            },
        ),
    ]
