# Generated by Django 5.2.17 on 2026-10-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0048_telegramreviewsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramPollingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=50, unique=True)),
                ('offset', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
