# Generated by Django 5.2.17 on 2026-10-07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0049_telegrampollingstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoringpreference",
            name="max_area",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name="scoringpreference",
            name="max_price",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scoringpreference",
            name="preferred_rooms",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="GeoZone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("tier", models.CharField(choices=[("A", "A — идеальная"), ("B", "B — хорошая"), ("C", "C — компромисс"), ("D", "D — не рассматриваю")], max_length=1)),
                ("geometry", models.JSONField(help_text="GeoJSON Polygon или MultiPolygon")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="geo_zones", to="auth.user")),
            ],
            options={"ordering": ("tier", "name", "id")},
        ),
        migrations.AddConstraint(
            model_name="geozone",
            constraint=models.UniqueConstraint(fields=("user", "name"), name="unique_user_geo_zone_name"),
        ),
    ]
