# Generated by Django 5.2.17 on 2026-10-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0050_scoringpreference_hard_filters_geozone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geozone",
            name="tier",
            field=models.CharField(
                choices=[
                    ("A", "Идеальная зона"),
                    ("B", "Хорошая зона"),
                    ("C", "Компромиссная зона"),
                    ("D", "Не рассматриваю"),
                ],
                max_length=1,
            ),
        ),
    ]
