# Generated by Django 5.2.17 on 2026-10-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0051_alter_geozone_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramlistingalert',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='telegramlistingalert',
            name='message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramlistingalert',
            name='message_kind',
            field=models.CharField(blank=True, choices=[('text', 'Текст'), ('photo', 'Фото')], max_length=10),
        ),
        migrations.AddField(
            model_name='telegramlistingalert',
            name='message_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='telegramlistingalert',
            name='score_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramlistingalert',
            name='score_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramlistingalert',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
